### ISSUE TITLE
kit permissions issue

### ISSUE THREAD

**Issue by brosephtheking** [uEssentials/uEssentials#133]
I can't get my permissions to work for default players. I have set up permissions correctly and they work on my friend's server, but when my guests use the commands nothing happens in chat, not even a "you don't have permission" or whatever

**Comment by WGSRangerWolf** [comment]
Please post your permissions.config

**Comment by brosephtheking** [comment]
https://www.dropbox.com/s/gqg970zy6yytxzs/Permissions.config.xml?dl=0

**Comment by WGSRangerWolf** [comment]
```
<Command>essentials.kit.Cop</command>
<Command>essentials..kit.Robber</Command>
<Command>essentials..kit.Hunter</Command>
```

**Comment by brosephtheking** [comment]
My friend did that and wasn't able to run kits, I also had that before and was unable to run the kits for guests.

**Comment by WGSRangerWolf** [comment]
Do you have the systems enabled. and do you have freaky's Kits?

**Comment by brosephtheking** [comment]
I also did "<Command>essentials.command.kits</Command>" and my guests can not see the kits.

**Comment by WGSRangerWolf** [comment]
Add me on steam http://steamcommunity.com/profiles/76561198067704805/

**Comment by brosephtheking** [comment]
I'm using this plugins kits and what are systems?

**Comment by WGSRangerWolf** [comment]
CURRENTLY UNABLE TO GET WORKING

**Comment by Punky69** [comment]
i just solved that problem for another guy try essentials.command.kit.<kitname> ps kit names are case sensitive so if name of kit is Cop permission should beessentials.command.kit.Cop
i sent leothedev msg abba that on skype but i guess he did not read it....

**Comment by persiafighter** [comment]
I'm just going to say... that in your config you have 1 big bug.

        <Command>essentials.command.kit.Cop</command>

The starting and ending clauses are different. Remember, it's all CaSE SEnSitIvE. Therefore, starting with `<Command>` expects you to finnish with `</Command>` not with `</command>` (LOWER CASE C)

That should fix the first part of the problem, second problem is you are leaving blank spaces and non-filled `<Command>` clauses (not sure non-filled `<Command>` clauses can cause any problems though):

        <Command>essentials.command.kit.Hunter</Command>
        <Command></Command>
        <Command></Command>
        <Command></Command>
        <Command></Command>
        <Command></Command>
        <Command></Command> 
 
         
      </Commands>

I recommend removing all those empty `<Command>` clauses and the extra spaces between the last clause and the ending `</Commands>` clause.

And lastly, a little advice from me, make every single clause `<Command>` instead of `<command>` as it might get a bit more confusing in the future (and it totally does).

And just in case you are too lazy to do this yourself, here is the fixed version of the default/guest group:
```
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Color>white</Color>
      <Members />
      <Commands>
        <Command>p</Command>
        <Command>compass</Command>
        <Command>rocket</Command>
        <Command>essentials.command.kits</Command>
        <Command>essentials.command.kit</Command>
        <Command>essentials.command.kit.Cop</Command>
        <Command>essentials.command.kit.Robber</Command>
        <Command>essentials.command.kit.Hunter</Command>
      </Commands>
      <ParentGroups />
    </Group>
```

**Comment by leonardosnt** [comment]
Wrong: <Command>essentials.command.kit.Hunter</Command>
Correct: <Command>essentials.kit.Hunter</Command>

**Comment by brosephtheking** [comment]
I should add that Ranger Wolf gave me a correct permissions file and we still faced the same issue.

**Comment by persiafighter** [comment]
Ranger Wolf gave you
```
<Command>essentials.kit.Cop</command>
<Command>essentials.kit.Robber</Command>
<Command>essentials.kit.Hunter</Command>
```
Which has that clause problem again. Just saying, wrong clause endings hurt.

**Comment by persiafighter** [comment]
Error logs with the script you submited first:
`Rocket.CoreException in Rocket.Core: System.Exception: Failed to deserialize XMLFileAsset: Permissions.config.xml ---> System.Xml.XmlException: 'Command' is expected  Line 16, position 47.`

[Image with the full error logs on the left, problem location on the right](http://i.imgur.com/HjfkEs8.png)

Error logs with the script fixed only with ranger's fix. (link to image, error is the same as above)
[img](http://i.imgur.com/qeacuoi.png)

Logs with the script that I posted above (and corrected due to me not editing `essentials.command.kit.Cop` to `essentials.kit.Cop` [thanks again leonardo for pointing this out to me, I keep forgetting])
[No Errors](http://i.imgur.com/8gQgbYA.png)

See now what I mean by clauses being case sensitive?

**Comment by WGSRangerWolf** [comment]
Yeah I missed that error my bad lol




*Have a amazing day,*

*Derrick McLean* (formaly known as waspgod, Rangerwolf)

**Comment by brosephtheking** [comment]
So now it says they don't have permissions. I set it up correctly based on what you guys have said.

**Comment by persiafighter** [comment]
@brosephtheking 

> So now it says they don't have permissions. I set it up correctly based on what you guys have said.

At least the first problem of nothing displaying when doing /kits or /kit Cop is fixed.

Now, I re-tested the config as I had it on the last picture where no problems showed up because of incorrect clauses and it appears that you might have copied and pasted the fixed default group incorrectly, as it does let me use /kit and /kits (of course since I didn't touch the kits config, no kits show up). [Proof that it works for me](http://i.imgur.com/c5gD7Z1.png) ingame. [Console Proof](http://i.imgur.com/WPAHSbo.png). And last, incase you are too lazy to DIY the fixing part of the config problems, here is a copy of the exact same config of all solved versions that I used (and kinda showed you): [Link](https://onedrive.live.com/redir?resid=A0D5E34B9DF98263!3884&authkey=!AMYNmugL-SylNfk&ithint=file%2ctxt)

**Comment by WGSRangerWolf** [comment]
This is working... Closing as this seems resolved.
